name: test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs: 
  build:
    name: Build Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun build

  storybook:
    name: Storybook Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: oven-sh/setup-bun@v2
        with:
          bun-version: latest
      - run: bun storybook